export enum Role {
    SUPER_ADMIN = "SUPER_ADMIN",
    LOGISTICS_MANAGER = "LOGISTICS_MANAGER",
    DISPATCHER = "DISPATCHER",
    FINANCE_MANAGER = "FINANCE_MANAGER",
    DRIVER_SUPERVISOR = "DRIVER_SUPERVISOR",
    MECHANIC = "MECHANIC",
    VIEWER = "VIEWER",
}
