import { DeliveryOrder } from './operational.schema';

export const dummyDOs: DeliveryOrder[] = [
  { id: '1', doNumber: 'DO-2026-09001', issueDate: '2026-09-01', customerName: 'PT. ABC Indonesia', shipper: 'PT. ABC Indonesia - Cikarang', consignee: 'PT. Jaya Retail - Surabaya', originCity: 'Cikarang, Bekasi', destCity: 'Gresik, Surabaya', cargoDesc: 'Spare Part Otomotif', qty: 120, unit: 'Karton', weightKg: 4800, volumeM3: 18.5, driverName: 'Slamet Rahardjo', vehiclePlate: 'B 9123 KXA', status: 'DELIVERED', specialNote: 'Handle with Care - Fragile Parts' },
  { id: '2', doNumber: 'DO-2026-09002', issueDate: '2026-09-02', customerName: 'PT. XYZ Nusantara', shipper: 'PT. XYZ - Bandung', consignee: 'PT. Sari Rasa - Semarang', originCity: 'Cimahi, Bandung', destCity: 'Kendal, Semarang', cargoDesc: 'Textile & Kain', qty: 80, unit: 'Roll', weightKg: 3200, volumeM3: 24.0, driverName: 'Budi Kurniawan', vehiclePlate: 'B 9876 KXB', status: 'IN_TRANSIT', specialNote: '-' },
  { id: '3', doNumber: 'DO-2026-09003', issueDate: '2026-09-02', customerName: 'PT. Maju Bersama', shipper: 'PT. Maju - Cikarang', consignee: 'PT. Berkah Jaya - Cirebon', originCity: 'Cikarang, Bekasi', destCity: 'Cirebon, Jawa Barat', cargoDesc: 'Bahan Makanan FMCG', qty: 250, unit: 'Sak', weightKg: 6500, volumeM3: 12.8, driverName: 'Andi Saputra', vehiclePlate: 'B 4567 KXC', status: 'DELIVERED', specialNote: 'Exp Date: Des 2026' },
  { id: '4', doNumber: 'DO-2026-09004', issueDate: '2026-09-03', customerName: 'PT. Sukses Makmur', shipper: 'PT. Sukses - Rungkut', consignee: 'PT. Kalimantan Trade - Balikpapan', originCity: 'Rungkut, Surabaya', destCity: 'Kariangau, Balikpapan', cargoDesc: 'Material Konstruksi (Besi)', qty: 40, unit: 'Batang', weightKg: 20000, volumeM3: 32.0, driverName: 'Hendra Gunawan', vehiclePlate: 'B 1289 KXD', status: 'DISPATCHED', specialNote: 'Izin ODOL diperlukan' },
  { id: '5', doNumber: 'DO-2026-09005', issueDate: '2026-09-03', customerName: 'PT. Sejahtera Abadi', shipper: 'PT. Sejahtera - Terboyo', consignee: 'PT. Solo Makmur - Solo', originCity: 'Terboyo, Semarang', destCity: 'Palur, Solo', cargoDesc: 'Elektronik Rumah Tangga', qty: 60, unit: 'Unit', weightKg: 1800, volumeM3: 9.5, driverName: 'Dedi Setiawan', vehiclePlate: 'B 1122 KXE', status: 'DRAFT', specialNote: 'Konfirmasi alamat tujuan' },
  { id: '6', doNumber: 'DO-2026-09006', issueDate: '2026-09-03', customerName: 'PT. Nusantara Jaya', shipper: 'PT. Nusantara - Marunda', consignee: 'PT. Sumatra Raya - Medan', originCity: 'Marunda, Jakarta', destCity: 'Belawan, Medan', cargoDesc: 'Consumer Goods (Sembako)', qty: 300, unit: 'Karton', weightKg: 9000, volumeM3: 28.5, driverName: 'Rudi Hermawan', vehiclePlate: 'B 3344 KXF', status: 'IN_TRANSIT', specialNote: 'Via Pelabuhan Tanjung Priok' },
  { id: '7', doNumber: 'DO-2026-09007', issueDate: '2026-08-31', customerName: 'PT. Pangan Nusantara', shipper: 'PT. Pangan - BJTI Surabaya', consignee: 'PT. Sulawesi Makmur - Makassar', originCity: 'BJTI, Surabaya', destCity: 'Soekarno Hatta, Makassar', cargoDesc: 'Beras Premium & Sembako', qty: 500, unit: 'Karung', weightKg: 25000, volumeM3: 35.0, driverName: 'Eko Prasetyo', vehiclePlate: 'B 5566 KXG', status: 'ARRIVED', specialNote: '-' },
  { id: '8', doNumber: 'DO-2026-09008', issueDate: '2026-09-01', customerName: 'PT. Motor Bersama', shipper: 'PT. Motor - Jababeka', consignee: 'PT. Tasik Parts - Tasikmalaya', originCity: 'Jababeka, Bekasi', destCity: 'Tasikmalaya, Jawa Barat', cargoDesc: 'Spare Part Sepeda Motor', qty: 100, unit: 'Dus', weightKg: 2000, volumeM3: 7.5, driverName: 'Agus Wijaya', vehiclePlate: 'B 7788 KXH', status: 'RETURNED', specialNote: 'Consignee tidak ada di lokasi' },
];
